# Generated by Django 6.0.2 on 2026-04-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=20, null=True)),
                ('situation', models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Explosion', 'Explosion'), ('Leakage', 'Leakage')], max_length=20, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='safeapp.robot')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, choices=[('Flame', 'Flame sensor'), ('Sound', 'Sound sensor'), ('Gas', 'Gas sensor')], max_length=20, null=True)),
                ('situation', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='safeapp.robot')),
            ],
        ),
    ]
